name: Refresh Profile

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Update Timestamp
        run: |
          DEPLOYED_ON=$(date -u +'%Y-%m-%d %H:%M UTC')
          sed -i "s/.*/**$DEPLOYED_ON**/" README.md

      - name: Commit Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Profile Autodeploy: $DEPLOYED_ON" || echo "No changes"
          git push
